UDWR Queue: Queue Class Reference
Queue Class Reference
Public Member Functions
Queue ()
bool isEmpty () const
bool isFull () const
size_t Queue::getSize() const
size_t Queue void dequeue () throw (QueueException)
void dequeue (QueueItemType &queueFront) throw (QueueException)
void getFront (QueueItemType &queueFront) const throw (QueueException)
Detailed Description
Class implementing a circular array based queue. This is a container class exhibiting First-In/First-Out (FIFO) functionality, where the interior items in the container are inaccessible. Items are inserted at the back of the queue. Items are withdrawn from the front of the queue. Because this container is based on a static array of fixed size, this container's capacity is limited and well-specified. Edit this file to change the queue size by changing MAX_QUEUE. Edit this file to change the item type by changing the typedef value.
Definition at line 43 of file QueueArray.h.
Constructor & Destructor Documentation
* Queue::Queue ()
Default constructor. Copy constructor and destructor are supplied by the compiler
Definition at line 20 of file QueueArray.cpp.
Member Function Documentation
bool Queue::isEmpty () const
Determines whether this queue is empty.
Precondition:
None.
Postcondition:
None.
Returns:
TRUE if this queue is empty; otherwise return FALSE.
Definition at line 24 of file QueueArray.cpp.
Referenced by dequeue(), and getFront().
bool Queue::isFull () const
Determines whether this queue is full.
Precondition:
None.
Postcondition:
None.
Returns:
TRUE if this queue is full; otherwise return FALSE.
Definition at line 29 of file QueueArray.cpp.
size_t Queue::getSize () const size_t Queue void Queue::dequeue () throw (QueueException)
Determines the queue capacity, i.e. the maximum count of items that the queue can hold.
Precondition:
None.
Postcondition:
None.
Returns:
a size_t value representing the queue capacity. Determines the count of items in the queue.
Precondition:
None.
Postcondition:
None.
Returns:
a size_t value representing the count of currently queued items. Determines the remaining queue capacity, i.e. the remaining count of items that may be enqueued.
Precondition:
None.
Postcondition:
None.
Returns:
a size_t value representing the remaining count.
Bug:
the returned value is incorrect and much too large.
Inserts an item at the back of the queue.
Precondition:
newItem is the item to be inserted && count < MAX_QUEUE.
Postcondition:
newItem resides at the back of the queue if successful && count <= MAX_QUEUE.
Exceptions:
QueueException if queue is full.
Parameters:
[in] newItem item to be enqueued. Deletes an item from the front of the queue.
Precondition:
0 < count <= MAX_QUEUE.
Postcondition:
If the queue is not empty, the item at the front of the queue is deleted && 0 <= count < MAX_QUEUE.
Exceptions:
QueueException if queue is empty.
void Queue::dequeue (QueueItemType & queueFront) throw (QueueException)
Retrieves and deletes an item from the front of the queue.
Precondition:
0 < count <= MAX_QUEUE.
Postcondition:
If the queue is not empty, queueFront contains the item from the front of the queue && the item at the front of the queue is deleted && 0 <= count < MAX_QUEUE.
Parameters:
[out] queueFront item to be dequeued.
Exceptions:
QueueException if queue is empty.
Definition at line 60 of file QueueArray.cpp.
References isEmpty().
void Queue::getFront (QueueItemType & queueFront) const throw (QueueException)
Retrieves an item from the front of the queue. The queue is not altered.
Precondition:
0 < count <= MAX_QUEUE.
Postcondition:
If the queue is not empty, queueFront contains the item from the front of the queue && 0 < count <= MAX_QUEUE.
Parameters:
[out] queueFront item from the front of the queue.
Exceptions:
QueueException if queue is empty.
Definition at line 74 of file QueueArray.cpp.
References isEmpty().
The documentation for this class was generated from the following files:
C:/Documents and Settings/aanda/My Documents/UDWR/QueueArray.h
C:/Documents and Settings/aanda/My Documents/UDWR/QueueArray.cpp